# This is the main CI workflow for pull requests to the dev branch.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

name: CI-CD

# Controls when the action will run. 
on:
  # Triggers the workflow in case of a push or pull request events
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or
# parallelly. As has been specified above, all the jobs below will be
# triggered either by a pull request or a merge of a pull request.
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu:24.04, ubuntu:25.04, debian:11-slim, debian:12-slim, debian:13-slim, fedora:41, fedora:42, almalinux:9.4 ]
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show OS info
        run: |
          echo "OS Info:"
          uname -a
          cat /etc/os-release
        
      - name: Setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: root-env
          channels: conda-forge
          auto-activate-base: false

      - name: Install ROOT
        shell: bash -l {0}
        run: |
          conda install -c conda-forge root_base -y

      - name: Run generator
        shell: bash -l {0}
        run: |
          conda activate root-env
          root --version
          root -l -q NeutronDecayGenerator.C
          root -l -q 'NeutronDecayGenerator.C("out",20,17,6,530,2,0.1)'
